Import('*')

SimObject(
    'Cachet.py',
    sim_objects = [
        'BaseCtrl',
        'SecCtrl',
        'CTRead',
        'CTWrite',
        'MTWrite',
        'CacheTree'
        ]
    )

Source('base_ctrl.cc')
Source('sec_ctrl.cc')
Source('ct_read.cc')
Source('ct_write.cc')
Source('mt_write.cc')
Source('cache_tree.cc')

DebugFlag('BaseCtrl')
DebugFlag('SecCtrl')
DebugFlag('CTRead')
DebugFlag('CTWrite')
DebugFlag('MTWrite')
DebugFlag('CacheTree')
