Import('*')

SimObject('SecCtrl.py', sim_objects = ['SecCtrl'])
SimObject('CTCtrl.py', sim_objects = ['CTRead', 'CTWrite'])

Source('sec_ctrl.cc')
Source('ct_read.cc')
Source('ct_write.cc')
Source('common.cc')

DebugFlag('SecCtrl')
DebugFlag('CTRead')
DebugFlag('CTWrite')
