Import('*')

SimObject(
    'SecCtrl.py',
    sim_objects = ['SecCtrl', 'CTRead', 'CTWrite', 'MTWrite']
    )

Source('sec_ctrl.cc')
Source('ct_read.cc')
Source('ct_write.cc')
Source('mt_write.cc')
Source('common.cc')

DebugFlag('SecCtrl')
DebugFlag('CTRead')
DebugFlag('CTWrite')
DebugFlag('MTWrite')
